# Project Euler Problem 29

import time

startTime = time.clock()

MAX = 100

distinctPowers = set([a ** b for a in range(2, MAX + 1) for b in range(2, MAX + 1)])

print("The number of distinct terms generated by a ^ b is {0}.".format(len(distinctPowers)))

print("Program execution took {0} seconds.".format(time.clock() - startTime))
